### ISSUE TITLE
Responsive tweak

### ISSUE THREAD

**Issue by dridslash** [Toufa7/PixelPong#16]
@Toufa7 don't forget about this tweak in home page

<img width="1182" alt="Screen Shot 2023-10-23 at 10 47 24 AM" src="https://github.com/Toufa7/PixelPong/assets/63309639/b576057b-6710-4ba7-9fbd-b87af44b6980">

**Comment by dridslash** [comment]
@Toufa7 it will be solved just by removing the additional routing to practice mode, wich we no longer obliged to do

**Comment by Toufa7** [comment]
Done
