### ISSUE TITLE
Time in chat

### ISSUE THREAD

**Issue by dridslash** [Toufa7/PixelPong#17]
When i send A message the time is displayed as follows

<img width="667" alt="Screen Shot 2023-10-25 at 11 31 05 AM" src="https://github.com/Toufa7/PixelPong/assets/63309639/f9bd1b34-df73-4338-8c8e-149e8d67103f">

-----------------------------------------------------------------------------
Also, you display the time round (PM/AM) only in the beginning

<img width="886" alt="Screen Shot 2023-10-25 at 11 32 44 AM" src="https://github.com/Toufa7/PixelPong/assets/63309639/dba64812-26fe-4189-8ec7-323f43a4b734">

**Comment by ibranad** [comment]
Issue fixed, please refer to commit No [#5f1a902](https://github.com/Toufa7/PixelPong/commit/5f1a90291c3d8bc6257d19740d229b0d0b5b7475)
