### ISSUE TITLE
Issue in Home Page

### ISSUE THREAD

**Issue by dridslash** [Toufa7/PixelPong#19]
<img width="629" alt="Screen Shot 2023-10-28 at 1 48 52 PM" src="https://github.com/Toufa7/PixelPong/assets/63309639/7b81f98d-d0ad-4fc1-b841-8406af99adab">

the Home Page doesn't get loaded due to this problem.

**Comment by Toufa7** [comment]
I'm not encountering this error more details please

**Comment by dridslash** [comment]
when i login and get redirected to home page this happens

**Comment by dridslash** [comment]
and im using chrome for the record

**Comment by dridslash** [comment]
<img width="1709" alt="Screen Shot 2023-10-28 at 2 14 45 PM" src="https://github.com/Toufa7/PixelPong/assets/63309639/eb714fa1-51c7-4469-9b7e-fbb7ed9e2658">

when i commented these two lines the problem no longer appears

**Comment by dridslash** [comment]
also the error seems to occur when we have to users connected
